# All proposals must follow the template, so disallow creating blank issues.
blank_issues_enabled: false

contact_links:
  - name: Share and discuss ideas
    url: https://github.com/godotengine/godot-proposals/discussions
    about: Discuss any idea related to improving Godot

  - name: Main Godot repository
    url: https://github.com/godotengine/godot
    about: Report bugs on the main Godot repository
